topic_codes = {0: 'geothermal', 1: 'wind', 2: 'hydropower', 3: 'biomass', 4: 'solar'}

#TODO: Makesure that there are no duplicate urls.

ENERGY_SEED_URLS = [('https://www.energy.gov/eere/geothermal/geothermal-faqs',0),
('https://www.energy.gov/eere/geothermal/geothermal-basics',0),
('https://www.energy.gov/eere/geothermal/geothermal-heat-pumps',0),
('https://www.irena.org/geothermal',0),
('https://www.canterbury.ac.nz/engineering/schools/mechanical/research/geothermal-energy/',0),
('https://www.dur.ac.uk/cerees/research/geothermal/',0),
('https://www.nature.com/subjects/geothermal-energy',0),
('https://geothermal.org/links.html',0),
('https://www.renewableenergyworld.com/wind-power/tech.html',1),
('https://www.energy.gov/eere/next-generation-wind-technology',1),
('https://www.wbif.eu/sectors/energy/sustainable-hydropower',2),
('http://www.alternativeenergyprimer.com/Hydropower.html',2),
('https://www.bbc.com/news/science-environment-46098118',2),
('https://www.ieahydro.org/links',2),
('https://www.puco.ohio.gov/industry-information/industry-topics/ohio-biomass-energy-links/',3),
('http://www.eubia.org/cms/wiki-biomass/bioenergy-links/',3), 
('http://www.alternativeenergyprimer.com/Biomass-Energy.html',3),
('http://indianpowersector.com/home/renewable-energy/biomass-power/',3),
('https://www.academia.edu/38711907/The_need_for_integrated_valuation_tools_to_support_decision-making_-The_case_of_cultural_ecosystem_services_sourced_from_geothermal_areas',0),
('http://www.academia.edu/Documents/in/Geothermal_Energy',0),
('https://www.sciencedirect.com/science/article/pii/037565059490037X',0),
('https://www.researchgate.net/publication/267637371_GEOTHERMAL_ENERGY_INDIAN_SCENARIO',0),
('https://www.energy.gov/sites/prod/files/2014/02/f7/geothermal_history_4_conversion.pdf',0),
('http://technav.ieee.org/tag/6204/geothermal-energy',0),
('https://unesdoc.unesco.org/ark:/48223/pf0000004490_eng',0),
('http://www.ipcc-wg3.de/report/IPCC_SRREN_Ch04.pdf',0),
('https://www.awea.org/wind-101/basics-of-wind-energy',1),
('https://openei.org/wiki/Wind_energy',1),
('https://www.nationalgeographic.com/environment/global-warming/wind-power/',1),
('https://www.irena.org/wind',1),
('https://en.wikipedia.org/wiki/Wind_turbine',1),
('https://www.energy.gov/eere/wind/how-do-wind-turbines-work',1),
('https://www.eia.gov/energyexplained/?page=biomass_home',3),
('https://en.wikipedia.org/wiki/Biomass',3),
('https://www3.epa.gov/climatechange//kids/solutions/technologies/biomass.html',3),
('https://www.nationalgeographic.org/encyclopedia/biomass-energy/',3),
('http://www.alternativeenergyprimer.com/Biomass-Energy.html',3),
('http://getwords.com/unit/62/ip:1/il:B',3),
('https://www.wur.nl/en/show/Components-from-biomass.htm',3),
('https://www.sciencedirect.com/science/article/pii/S0961953496000517',3),
('https://ypte.org.uk/factsheets/renewable-energy-biomass-energy/the-theory-of-biomass-energy',3),
('https://www.conserve-energy-future.com/category/pollution',3),
('https://onlinelibrary.wiley.com/doi/full/10.1002/ceat.201600259',3),
('https://www.euractiv.com/section/energy/opinion/biomass-is-key-for-realising-climate-goals-and-implementing-elements-of-circular-economy/',3),
("https://www.seia.org/", 4),
("https://www.solarenergy.org/", 4),
("https://www.journals.elsevier.com/solar-energy", 4),
("https://www.britannica.com/science/solar-energy", 4),
("https://www.energysage.com/solar/", 4),
("https://www.nationalgeographic.com/environment/global-warming/solar-power/", 4),
("https://www.ases.org/", 4),
("https://www.edx.org/course/solar-energy", 4),
("https://arena.gov.au/about/what-is-renewable-energy/solar-energy/", 4),
("https://www.greenmatch.co.uk/solar-energy/solar-panels", 4),
("https://www.energysavingtrust.org.uk/renewable-energy/electricity/solar-panels", 4),
("https://us.sunpower.com/home-solar/solar-cell-technology-solutions", 4),
("https://www.forbes.com/sites/gauravsharma/2019/01/17/solar-power-outperforming-wind-as-renewable-energy-becomes-commonplace/#29ff16bd6ea0", 4),
("https://www.openaccessgovernment.org/solar-energy-farms/56768/", 4),
("https://en.wikipedia.org/wiki/Solar_energy", 4),
("https://www.osti.gov/biblio/5152645", 4),
("http://adsabs.harvard.edu/abs/2004reen.book.....B", 4),
("https://www.pnas.org/content/103/43/15729/", 4),
("https://pubs.acs.org/doi/abs/10.1021/ic0508371", 4),
("https://www.sciencedirect.com/science/article/pii/S092702480700205X", 4),
("https://www.osti.gov/biblio/6408304", 4),
("https://ieeexplore.ieee.org/abstract/document/1318699", 2),
("https://ieeexplore.ieee.org/abstract/document/260826", 2),
("https://www.sciencedirect.com/science/article/pii/S0301421504001892", 2),
("https://ieeexplore.ieee.org/abstract/document/574921", 2),
("https://www.sciencedirect.com/science/article/pii/S0301421504000874", 2),
("https://www.sciencedirect.com/science/article/pii/S1364032111001924", 2),
("https://ieeexplore.ieee.org/abstract/document/5325712", 2),
("https://www.sciencedirect.com/science/article/pii/S0306261902000454", 2),
("https://www.sciencedirect.com/science/article/pii/S1364032113008575", 2),
("https://ieeexplore.ieee.org/abstract/document/744500", 2)]
